[pytest]
addopts = -m "not slow"
markers =
    slow: slow running tests that may require network access
filterwarnings =
    ignore:builtin type SwigPyObject has no __module__ attribute:DeprecationWarning:importlib._bootstrap
    ignore:builtin type SwigPyPacked has no __module__ attribute:DeprecationWarning:importlib._bootstrap
    ignore::DeprecationWarning:torch
    ignore::UserWarning:mlflow
